INSERT INTO photos (
  id,
  source_id,
  storage_file_id,
  file_path,
  file_name,
  file_ext,
  file_size,
  mime_type,
  content_hash,
  shot_at,
  created_at_fs,
  modified_at_fs,
  sort_time,
  width,
  height,
  exif_json,
  gps_lat,
  gps_lng,
  deleted_at,
  created_at,
  updated_at
) VALUES (
  :id,
  :source_id,
  :storage_file_id,
  :file_path,
  :file_name,
  :file_ext,
  :file_size,
  :mime_type,
  :content_hash,
  :shot_at,
  :created_at_fs,
  :modified_at_fs,
  :sort_time,
  :width,
  :height,
  :exif_json,
  :gps_lat,
  :gps_lng,
  :deleted_at,
  :created_at,
  :updated_at
)
ON CONFLICT(source_id, storage_file_id) DO UPDATE SET
  file_path = excluded.file_path,
  file_name = excluded.file_name,
  file_ext = excluded.file_ext,
  file_size = excluded.file_size,
  mime_type = excluded.mime_type,
  content_hash = excluded.content_hash,
  shot_at = excluded.shot_at,
  created_at_fs = excluded.created_at_fs,
  modified_at_fs = excluded.modified_at_fs,
  sort_time = excluded.sort_time,
  width = excluded.width,
  height = excluded.height,
  exif_json = excluded.exif_json,
  gps_lat = excluded.gps_lat,
  gps_lng = excluded.gps_lng,
  deleted_at = excluded.deleted_at,
  updated_at = excluded.updated_at;
